version: '3'
services:
  frontend:
    build:
      context: ./ingredient-harmony-frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./ingredient_harmony_backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
